/* ----------------------------- DOCUMENT DATA ----------------------------- */

export const DOCUMENTS = [
  { id: "aadhaar", name: "Aadhaar Card", cat: "Personal", icon: "User", desc: "Identity proof of buyer and seller.", what: "A 12-digit identity number issued by UIDAI, used for identity and address verification at the registration office.", why: "The Sub-Registrar captures biometrics against Aadhaar at registration. Both buyer and seller need it.", where: "UIDAI portal or any Aadhaar Seva Kendra", fee: "Free (₹50 for update)", mandatory: true },
  { id: "pan", name: "PAN Card", cat: "Personal", icon: "FileText", desc: "Permanent Account Number card.", what: "The tax identification number issued by the Income Tax Department.", why: "Mandatory for any property transaction above ₹5 lakh, and reported in the annual information statement.", where: "NSDL or UTIITSL portal", fee: "₹107 approx", mandatory: true },
  { id: "photo", name: "Passport Size Photographs", cat: "Personal", icon: "User", desc: "Recent photographs of both parties.", what: "Standard passport size colour photographs, usually 4 copies per party.", why: "Affixed on the sale deed and the registration form at the Sub-Registrar Office.", where: "Any photo studio", fee: "₹100 – ₹200", mandatory: true },
  { id: "address", name: "Address Proof", cat: "Personal", icon: "Home", desc: "Utility bill, rent agreement or passport.", what: "Any government-accepted document showing your current residential address.", why: "The registration form records the present address of both parties.", where: "Utility provider, municipal office or passport office", fee: "Varies", mandatory: true },
  { id: "saledeed", name: "Sale Deed", cat: "Property", icon: "FileSignature", desc: "The registered deed transferring ownership.", what: "The core legal document that records the transfer of ownership from seller to buyer.", why: "This is the document that actually makes you the owner. Everything else supports it.", where: "Drafted by an advocate, registered at the Sub-Registrar Office", fee: "Drafting ₹2,000 – ₹15,000", mandatory: true },
  { id: "titledeeds", name: "Previous Title Deeds", cat: "Property", icon: "Folder", desc: "Chain of past ownership documents.", what: "The set of earlier registered deeds showing how the property moved from owner to owner.", why: "A broken chain is the classic sign of a disputed title. Ask for at least 30 years of history.", where: "Seller, or certified copies from the Sub-Registrar Office", fee: "₹100 – ₹500 per certified copy", mandatory: true },
  { id: "extract", name: "Land Record Extract", cat: "Property", icon: "FileText", desc: "State record of rights (7/12, RTC, Khatauni, Patta).", what: "The state revenue record showing the current holder, area, tenure and any registered charge on the land.", why: "This is the government's own statement of who holds the land. It should be dated within the last 3 months.", where: "State land records portal or Tehsil / Taluk office", fee: "₹15 – ₹100", mandatory: true },
  { id: "ec", name: "Encumbrance Certificate", cat: "Legal", icon: "ShieldCheck", desc: "Proof the land is free from legal dues.", what: "A certificate listing every registered transaction on the property during a chosen period.", why: "It reveals hidden mortgages and past sales. A clean EC for 13 to 30 years is what you are looking for.", where: "Sub-Registrar Office or the state registration portal", fee: "₹200 – ₹500", mandatory: true },
  { id: "tax", name: "Property Tax Receipt", cat: "Property", icon: "IndianRupee", desc: "Latest tax payment receipt.", what: "The receipt from the local body showing property tax has been paid up to date.", why: "Unpaid tax becomes your liability after purchase, and the municipal record also confirms possession.", where: "Municipal Corporation, Gram Panchayat or municipal portal", fee: "Free copy", mandatory: true },
  { id: "mutation", name: "Mutation Records", cat: "Property", icon: "RefreshCw", desc: "Proof of the last revenue record update.", what: "The mutation entry showing when the current holder's name was added to the revenue record.", why: "If the seller never completed mutation after their own purchase, their record is incomplete.", where: "Tehsil / Taluk office", fee: "₹50 – ₹200", mandatory: false },
  { id: "noc", name: "No Objection Certificate", cat: "Legal", icon: "CheckCircle2", desc: "NOC from the relevant authority.", what: "A written confirmation from a society, planning authority or department that they do not object to the transfer.", why: "Needed for society flats, land near defence or coastal zones, and some agricultural transfers.", where: "Society office, development authority or concerned department", fee: "₹500 – ₹5,000", mandatory: false },
  { id: "khata", name: "Khata / Khasra Certificate", cat: "Property", icon: "ClipboardList", desc: "Local body property account record.", what: "The account maintained by the local body that links the property to its tax record.", why: "Required in states like Karnataka for tax payment, building permission and loan approval.", where: "Municipal Corporation or Panchayat", fee: "₹125 – ₹500", mandatory: false },
  { id: "survey", name: "Land Survey / Measurement Map", cat: "Property", icon: "MapPin", desc: "Official survey map of the plot.", what: "A measured plan of the plot issued by the survey department, showing boundaries and area.", why: "Boundary disputes with neighbours are common. A fresh survey map settles what you are actually buying.", where: "District Land Records / Survey Office", fee: "₹500 – ₹3,000", mandatory: false },
  { id: "conversion", name: "NA / Conversion Order", cat: "Legal", icon: "Landmark", desc: "Order converting agricultural land to non-agricultural use.", what: "The Collector's order permitting the land to be used for residential, commercial or industrial purposes.", why: "Without it, any construction is unauthorised and no bank will fund the purchase.", where: "Collector Office", fee: "As per conversion premium", mandatory: false },
  { id: "heir", name: "Legal Heir / Succession Certificate", cat: "Legal", icon: "Users", desc: "Proof of who inherits the property.", what: "A certificate naming the legal heirs of a deceased owner.", why: "Essential when buying inherited land, so that every heir is identified and consents to the sale.", where: "Tehsildar Office or Civil Court", fee: "₹500 – ₹5,000", mandatory: false },
  { id: "poa", name: "Power of Attorney", cat: "Legal", icon: "Scale", desc: "Authorisation when someone signs on another's behalf.", what: "A registered document authorising a named person to act for the owner.", why: "If the seller is not signing personally, the POA must be registered and still valid on the date of sale.", where: "Sub-Registrar Office", fee: "₹500 – ₹2,000", mandatory: false },
];

export const DOC_CATS = ["All Documents", "Personal", "Property", "Legal"];
